apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartops-app
  labels:
    app: smartops
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: smartops
  template:
    metadata:
      labels:
        app: smartops
    spec:
      containers:
      - name: smartops
        image: smartops:v14
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
